[workspace]
resolver = "3"
members = [
    "crates/nixcache-core",
    "crates/nixcache-oci",
    "crates/nixcache-proxy",
    "crates/nixcache-builder",
    "crates/nixcache-worker",
]

[workspace.dependencies]
nixcache-core = { path = "crates/nixcache-core" }
nixcache-oci = { path = "crates/nixcache-oci" }
async-trait = "0.1"
bytes = "1"
http = "1"
axum = { version = "0.8", features = ["http2"] }
tokio = { version = "1" }
reqwest = { version = "0.13", default-features = false, features = ["json", "stream", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
futures-util = "0.3"
tokio-util = { version = "0.7" }
tracing = "0.1"
tracing-subscriber = "0.3"
sha2 = "0.11"
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.17"
thiserror = "2.0"
base64 = "0.22"
clap = { version = "4.6", features = ["derive", "env"] }
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
wiremock = "0.6"
moka = { version = "0.12", features = ["future"] }
async-compression = { version = "0.4", features = ["tokio", "xz"] }
