[package]
name = "nixcache-oci"
version = "0.1.0"
edition = "2024"

[dependencies]
nixcache-core = { workspace = true }
nixcache-utils = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
futures-util = { workspace = true }
futures-channel = { workspace = true }
futures-executor = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
web-time = { workspace = true }
arc-swap = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
scc = { workspace = true }
crossbeam-queue = { workspace = true }
loom = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
loom = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
