[package]
name = "nixcache-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace crates
nixcache-cli = { workspace = true }
nixcache-core = { workspace = true }
nixcache-oci = { workspace = true }
nixcache-oci-backend = { workspace = true, features = ["tokio-reqwest"] }
nixcache-utils = { workspace = true }

# Async runtime & networking
bytes = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["io"] }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Compression
async-compression = { workspace = true }

# Observability
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# CLI & Utilities
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
mimalloc = { workspace = true }
num_cpus = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
